[package]
name = "message-bus"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
async-trait = "0.1"

[dev-dependencies]
tokio-test = "0.4"