[package]
name = "collections-basics"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "collections-basics"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
